"""empty message

Revision ID: a32bed251d2a
Revises: 8d50c7a3a756
Create Date: 2024-04-21 20:53:58.606502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32bed251d2a'
down_revision = '8d50c7a3a756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('User_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bill_user_id', 'user', ['User_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bill_user_id', type_='foreignkey')
        batch_op.drop_column('User_id')

    # ### end Alembic commands ###
